pipeline {
  agent none
  stages {
    stage('frontend') {
        docker {image 'node:16-alpine'}
      steps{
      sh 'node --version'
    }
    }
    
    stage('db') {
        docker {image 'mysql:latest'}
      steps {
        sh 'node --version'
      }
    }
    
  }
}
